### ISSUE TITLE
discrepancy in circom compiling time

### ISSUE THREAD

**Issue by katat** [zk-email-verify/zk-regex#2]
Somehow the circom compiler takes a significantly long time to compile the same circuit with different signal variable names. 

For example, the naming difference in [this code](https://github.com/zk-email-verify/zk-regex/compare/f72559911a1089eb20cc42c9bac8d20710a37a37..e81c6ebf4a69a1a72635b6dd0e7aa328d2f6941f) introduces a significant difference in compiling time. This is quite strange as the naming difference isn't introduced a difference in the circuit logic. The compiling time should be the same when the signal variable naming differs.

For now, the naming of the variables is reverted to make the compilation faster. But in the long run, this would be a potential issue in maintenance. This issue is for tracking the issue.

**Comment by alrubio** [comment]
Thanks for reporting. This can be related to the simplification phase, which is a costly process that uses some heuristics that can be affected by the order in which signals are treated. In general, signal names does not affect the process but component names may affect it. Can you provide us with the full circom circuit? I tried to download them from the git but the files cannot be compiled.
If so we can see what's happening.
