### ISSUE TITLE
doesn't match regex_to_circom

### ISSUE THREAD

**Issue by Divide-By-0** [zk-email-verify/zk-regex#5]
For the header regex, this command ```yarn compile '(\r\n|\x80)(to|from):((a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9| |_|.|"|@|-)+<)?(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|_|.|-)+@(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|_|.|-)+>?\r\n'``` doesn't match the output from regex_to_circom. Here, it wrongly asserts that there are 3 accept states, but in the python + js version, it has 1 accept state and passes.

**Comment by katat** [comment]
this [PR](https://github.com/zk-email-verify/zk-regex/pull/6) should cover the fix to this. I haven't run a test for this case yet, so let me know if it works.

**Comment by Divide-By-0** [comment]
Great! Looking forward to seeing those changes in the README/comments/documentation.
